"""装配层：把 Ports / Adapters / Tools / Runner / ApplicationService 组装起来。"""

from security_diagnosis_harness.bootstrap.container import (
    ACCESS_CASES_DATA_PATH,
    ALARM_CASES_DATA_PATH,
    CAMERA_CASES_DATA_PATH,
    DEFAULT_DEVICE_DATA_PATH,
    PHASE0_TOOLS,
    PHASE1_TOOLS,
    PHASE2_TOOLS,
    PHASE3_TOOLS,
    PHASE4_TOOLS,
    Container,
    build_access_registry,
    build_access_responder,
    build_alarm_registry,
    build_alarm_responder,
    build_camera_black_screen_responder,
    build_container,
    build_phase1_container,
    build_phase2_container,
    build_phase3_container,
    build_phase4_container,
    build_registry,
    build_service,
)

__all__ = [
    "ACCESS_CASES_DATA_PATH",
    "ALARM_CASES_DATA_PATH",
    "CAMERA_CASES_DATA_PATH",
    "DEFAULT_DEVICE_DATA_PATH",
    "PHASE0_TOOLS",
    "PHASE1_TOOLS",
    "PHASE2_TOOLS",
    "PHASE3_TOOLS",
    "PHASE4_TOOLS",
    "Container",
    "build_access_registry",
    "build_access_responder",
    "build_alarm_registry",
    "build_alarm_responder",
    "build_camera_black_screen_responder",
    "build_container",
    "build_phase1_container",
    "build_phase2_container",
    "build_phase3_container",
    "build_phase4_container",
    "build_registry",
    "build_service",
]
